name: Feature Request 💡
description: Request a new feature
title: "[FEATURE] <title>"
labels: ["Feature Request", "Needs Triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description of the feature you are requesting.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: A concise description of the use case for this feature.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are requesting!
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 0
    validations:
      required: true
